# Built with Jekyll 3.2.0

# Setup
title:               Expanded Interfaces
tagline:             ''
description:         'A speculative exploration of the interface; the relational boundary between humans, computation and matter.'
url:                 'https://expandedinterface.github.io/'
baseurl:             ''

# About/contact
author:
  name:              Expanded Interfaces
  url:
  email:

# Random redirect settings
random_redirect:
pages: true

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown, green
color-scheme:

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for artifacts
collections:
  artifacts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Exclusions from the final site
exclude:
  - optional
  - vendor
