# Built with Jekyll 3.2.0

# Setup
title:               Expanded Interfaces
tagline:             'a jekyll theme for minimal editions'
description:         'A speculative exploration of the interface; the relational boundary between humans, computation and matter.'
url:                 'https://tingeber.github.io/expandedinterfaces'
baseurl:             '/expandedinterfaces'

# About/contact
author:
  name:              Expanded Interfaces
  url:
  email:

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: cyan

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
